### ISSUE TITLE
use Angular commit guidelines

### ISSUE THREAD

**Issue by willworks** [M6Guys/interesting-code#1]
> it wil be much helpful to create changeLog

- feat: A new feature
- fix: A bug fix
- docs: Documentation only changes
- style: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
- refactor: A code change that neither fixes a bug nor adds a feature
- perf: A code change that improves performance
- test: Adding missing tests
- chore: Changes to the build process or auxiliary tools and libraries such as documentation generation

**Comment by PupateYf** [comment]
pretty good
